STORIES = [
    {
        "id": 1,
        "title": "The Vanishing Hour",
        "icon": "🕰️",
        "genre": "Mystery / time-loop investigation",
        "difficulty": "Intermediate → Advanced",
        "hook": "A city loses all memory of one specific hour every night.",
        "opening": "At 3:00 AM, Veridian loses an hour. Your terminal is the only system still holding fragments of what happened.",
        "reveal": "The mystery is caused by inconsistent records across independent systems. You reconstruct the truth with relational queries, normalization, indexes, transactions and recovery.",
        "primary": "Modeling + SQL",
        "mode": "SQL investigation",
        "topics": ["SELECT", "JOIN", "GROUP BY", "Normalization", "Indexing", "Transactions", "Recovery", "Partitioning"],
    },
    {
        "id": 2,
        "title": "Convoy Zero",
        "icon": "🚀",
        "genre": "Sci-fi / interplanetary logistics",
        "difficulty": "Advanced",
        "hook": "Three colonies cannot reliably communicate, but all depend on the same cargo.",
        "opening": "Light-lag and blackouts separate three colony ledgers. A single crate can be allocated twice.",
        "reveal": "Local ledgers behave like distributed database nodes. You must reason about concurrency, replication, CAP trade-offs and reconciliation.",
        "primary": "Distributed consistency",
        "mode": "Decision simulator",
        "topics": ["ACID", "Concurrency", "Replication", "CAP", "Eventual Consistency", "Partitioning"],
    },
    {
        "id": 3,
        "title": "The Silence Between Signals",
        "icon": "📡",
        "genre": "First-contact / signals intelligence",
        "difficulty": "Advanced",
        "hook": "Half a billion radio bursts hide one repeating pattern.",
        "opening": "The Aurelia Array records faster than analysts can search. A pattern may be hidden in the noise.",
        "reveal": "The mystery becomes a performance problem: scans, indexes, composite indexes, materialized views and OLTP/OLAP separation.",
        "primary": "Indexing + query plans",
        "mode": "Query-plan visualizer",
        "topics": ["B-Tree", "Index Scan", "Sequential Scan", "Composite Index", "Materialized View", "OLAP"],
    },
    {
        "id": 4,
        "title": "The Man Who Remembered Too Much",
        "icon": "🧠",
        "genre": "Psychological sci-fi / neural archive",
        "difficulty": "Intermediate → Advanced",
        "hook": "A neural implant contains multiple contradictory versions of one person's life.",
        "opening": "Elias Voss remembers two marriages, two jobs and two childhoods. The implant says every memory is authentic.",
        "reveal": "The real problem is redundant facts drifting apart. Functional dependencies and normalization become the way to repair the schema.",
        "primary": "Normalization",
        "mode": "Schema surgery",
        "topics": ["FDs", "1NF", "2NF", "3NF", "BCNF", "Denormalization", "Constraints"],
    },
    {
        "id": 5,
        "title": "The Last Broadcast",
        "icon": "🔥",
        "genre": "Disaster response / crisis coordination",
        "difficulty": "Advanced",
        "hook": "Three agencies are giving residents three different evacuation routes.",
        "opening": "A wildfire is spreading. Fire command, police and transit are all updating overlapping route records.",
        "reveal": "The contradictions are concurrency anomalies. You diagnose dirty reads, non-repeatable reads, phantom reads, lost updates, locks and deadlocks.",
        "primary": "Transactions + concurrency",
        "mode": "Locking simulator",
        "topics": ["ACID", "Isolation", "Dirty Read", "Locks", "2PL", "Deadlock", "Recovery"],
    },
    {
        "id": 6,
        "title": "The Depth Ledger",
        "icon": "🏺",
        "genre": "Archaeological discovery",
        "difficulty": "Intermediate → Advanced",
        "hook": "An ancient merchant ledger contains 200,000 transactions and a hidden conspiracy.",
        "opening": "Digitized clay tablets reveal trade patterns spanning three centuries.",
        "reveal": "The investigation teaches analytical SQL, joins, window functions, CTEs, set operations, indexing and cost-based thinking.",
        "primary": "Advanced SQL",
        "mode": "SQL puzzle",
        "topics": ["JOIN", "GROUP BY", "Window Functions", "CTE", "UNION", "Indexes", "Query Plans"],
    },
    {
        "id": 7,
        "title": "The Colony That Forgot Its Laws",
        "icon": "⚖️",
        "genre": "Autonomous robot society",
        "difficulty": "Expert",
        "hook": "Twelve robot sectors have different versions of the same rulebook.",
        "opening": "Two robots are about to make opposite decisions because both believe their copy of the law is authoritative.",
        "reveal": "Replica divergence forces you into leader/follower replication, failover, quorum writes and consensus.",
        "primary": "Consensus + replication",
        "mode": "Distributed cluster visualizer",
        "topics": ["Replication", "Leader", "Failover", "Quorum", "Consensus", "Fault Tolerance"],
    },
    {
        "id": 8,
        "title": "The Machine That Lied",
        "icon": "🤖",
        "genre": "Cyber investigation / AI accountability",
        "difficulty": "Expert / Research-level",
        "hook": "An AI gave two departments contradictory advice from supposedly the same report.",
        "opening": "Both departments have screenshots. The AI's logs insist it never contradicted itself.",
        "reveal": "Different reads of different committed versions reveal isolation behavior. MVCC and snapshot isolation become the solution.",
        "primary": "MVCC + isolation",
        "mode": "Timeline visualizer",
        "topics": ["Isolation", "MVCC", "Snapshot", "Temporal Data", "Audit", "Recovery"],
    },
    {
        "id": 9,
        "title": "The Forgotten Archive",
        "icon": "🗃️",
        "genre": "Historical mystery / records restoration",
        "difficulty": "Beginner → Intermediate",
        "hook": "A museum's paper archive is collapsing because every department keeps its own version of the truth.",
        "opening": "The museum has separate ledgers for visitors, artifacts, loans and curators. Nobody agrees on which record is current.",
        "reveal": "You discover the weaknesses of file-based systems and gradually build the idea of a DBMS, data independence and three-schema architecture.",
        "primary": "DBMS foundations",
        "mode": "Drag-and-drop architecture",
        "topics": ["File Systems", "DBMS", "Data Dependency", "3-Schema", "Data Independence", "Lifecycle"],
    },
    {
        "id": 10,
        "title": "The Blueprint That Couldn't Exist",
        "icon": "🏗️",
        "genre": "Impossible city / systems design",
        "difficulty": "Intermediate",
        "hook": "A city blueprint contains buildings that cannot legally exist under its own rules.",
        "opening": "You must reconstruct a city from entities, relationships and constraints before construction can begin.",
        "reveal": "The city becomes an ER and relational-model laboratory. You model entities, relationships, specialization, constraints, then translate them into relational operations.",
        "primary": "ER + relational theory",
        "mode": "Modeling + algebra puzzle",
        "topics": ["ER", "Cardinality", "Constraints", "Generalization", "Specialization", "Relational Algebra", "Calculus"],
    },
    {
        "id": 11,
        "title": "The Impossible Contract",
        "icon": "📜",
        "genre": "Legal thriller / contract reconstruction",
        "difficulty": "Intermediate → Advanced",
        "hook": "A contract archive contains agreements that are individually valid but impossible to combine consistently.",
        "opening": "Thousands of clauses repeat the same facts in different structures. One corrupted agreement may change the outcome of a billion-dollar case.",
        "reveal": "You progressively eliminate anomalies with 1NF through 5NF, then deliberately denormalize where performance demands it. SQL DDL/DML and advanced predicates finish the case.",
        "primary": "Normalization 1NF–5NF + SQL",
        "mode": "Fill-the-gap schema lab",
        "topics": ["1NF", "2NF", "3NF", "BCNF", "4NF", "5NF", "DDL", "DML", "EXISTS"],
    },
]
